---
- name: Setup Web Stack on Rocky Linux 8
  hosts: cloud.wefixdit.com
  become: yes
  vars:
    http_port: 80
    https_port: 443
    nginx_cache_path: /var/cache/nginx
    php_fpm_pool_name: www
    postgresql_dbname: mydatabase
    postgresql_user: myuser
    postgresql_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
    redis_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"

  tasks:
    - name: Ensure EPEL repository is installed
      dnf:
        name: epel-release
        state: present

    - name: Install Apache, PHP-FPM, Redis, and PostgreSQL
      dnf:
        name:
          - httpd
          - php-fpm
          - php-pgsql
          - php-redis
          - postgresql-server
          - postgresql-contrib
          - redis
        state: present

    - name: Start and enable Apache service
      systemd:
        name: httpd
        enabled: yes
        state: started

    - name: Configure PHP-FPM
      template:
        src: templates/php-fpm.conf.j2
        dest: /etc/php-fpm.d/{{ php_fpm_pool_name }}.conf
      notify: restart php-fpm

    - name: Start and enable PHP-FPM service
      systemd:
        name: php-fpm
        enabled: yes
        state: started

    - name: Start and enable Redis service
      systemd:
        name: redis
        enabled: yes
        state: started

    - name: Initialize PostgreSQL database
      become_user: postgres
      command: /usr/bin/initdb --locale=C -D /var/lib/pgsql/data/
      args:
        creates: /var/lib/pgsql/data/postgresql.conf

    - name: Start and enable PostgreSQL service
      systemd:
        name: postgresql
        enabled: yes
        state: started

    - name: Create PostgreSQL database
      become_user: postgres
      postgresql_db:
        name: "{{ postgresql_dbname }}"

    - name: Create PostgreSQL user with password
      become_user: postgres
      postgresql_user:
        db: "{{ postgresql_dbname }}"
        name: "{{ postgresql_user }}"
        password: "{{ postgresql_password }}"
        priv: ALL

    - name: Configure Redis to require a password
      lineinfile:
        path: /etc/redis.conf
        regexp: '^#?requirepass'
        line: "requirepass {{ redis_password }}"
        backup: yes
      notify: restart redis

    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Configure Nginx as reverse proxy and caching server
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started

  handlers:
    - name: restart php-fpm
      systemd:
        name: php-fpm
        state: restarted

    - name: restart redis
      systemd:
        name: redis
        state: restarted

  tasks:
    - name: Display generated passwords
      debug:
        msg: |
          PostgreSQL user '{{ postgresql_user }}' password: {{ postgresql_password }}
          Redis password: {{ redis_password }}
